#
#server:
#  servlet:
#    context-path: /price-engine

server:
  port: 8080

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: websocket for price feed
  try-host: http://localhost:${server.port}

spring:
  web:
    resources:
      static-locations[0]: "file:src/main/resources/static/"
      static-locations[1]: "classpath:/static/"
